-- Create deletion_logs table to store audit information and enable restoration of deleted records
CREATE TABLE IF NOT EXISTS public.deletion_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    record_id text not null,
    display_name text, -- e.g. Client Name for quick reference
    data jsonb not null,
    deleted_by text,
    deleted_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.deletion_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies to allow access (Adjust as needed for production)
DROP POLICY IF EXISTS "Enable all for deletion_logs" ON public.deletion_logs;
CREATE POLICY "Enable all for deletion_logs" ON public.deletion_logs FOR ALL USING (true);
