-- Create Leads Table for CRM Module
CREATE TABLE IF NOT EXISTS public.leads (
    id bigint generated by default as identity primary key,
    sr_no text,
    sales_form_no text,
    sales_form_date text,
    source text,
    stage text,
    category text,
    location text,
    project_name text,
    developer text,
    configuration text,
    const_status text,
    owner_name text,
    finalizing_authority text,
    site_incharge text,
    architect text,
    remarks text,
    created_at timestamptz default now()
);

-- Enable RLS
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Policies (Idempotent)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable read access for all users' AND tablename = 'leads' AND schemaname = 'public') THEN
        CREATE POLICY "Enable read access for all users" ON public.leads FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable insert access for all users' AND tablename = 'leads' AND schemaname = 'public') THEN
        CREATE POLICY "Enable insert access for all users" ON public.leads FOR INSERT WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable update access for all users' AND tablename = 'leads' AND schemaname = 'public') THEN
        CREATE POLICY "Enable update access for all users" ON public.leads FOR UPDATE USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Enable delete access for all users' AND tablename = 'leads' AND schemaname = 'public') THEN
        CREATE POLICY "Enable delete access for all users" ON public.leads FOR DELETE USING (true);
    END IF;
END
$$;

-- Seed Initial Data
INSERT INTO public.leads (sr_no, sales_form_no, sales_form_date, source, stage, category, location, project_name, developer, configuration, const_status, owner_name, finalizing_authority, site_incharge, architect, remarks)
VALUES 
('1', 'AS001', '10/12/2012', 'WOM', 'qualified', 'HOT', 'Santakruz', 'Runwal symphony', 'Runwal developers pvt.ltd', 'Gr+Bas+Pod+15fl', '15 Fl compl', 'Sandeep runwal', 'Manisha Thakur', 'Mr.sameer patil', 'Vivek bhole', ''),
('2', 'AS013/1', '', 'referral', 'qualified', 'Hot', 'Borivali', 'samarpan exotica', 'Kanakia Spaces', '', '', '', 'Sabir', '', '', 'Call on 6 pm'),
('3', 'AS013/2', '16/03/2013', 'referral', 'Quoted', 'Hot', 'Borivali', 'satra park', 'satra group', '', '80%', '', 'vinod pokharkar 987004200', '', '', 'incorrect number 19/08/16')
ON CONFLICT (id) DO NOTHING;
