-- Create missing tables for Services, Payments, and Invoices

-- 1. Services Table
CREATE TABLE IF NOT EXISTS public.services (
    id bigint generated by default as identity primary key,
    service_id text unique,
    client_id bigint references public.clients(id) on delete cascade,
    service_type text,
    service_date date,
    technician_name text,
    status text,
    created_at timestamptz default now()
);

-- 2. Payments Table
CREATE TABLE IF NOT EXISTS public.payments (
    id bigint generated by default as identity primary key,
    payment_id text unique,
    client_id bigint references public.clients(id) on delete cascade,
    amount decimal(12,2),
    payment_date date,
    payment_method text,
    status text,
    created_at timestamptz default now()
);

-- 3. Invoices Table
CREATE TABLE IF NOT EXISTS public.invoices (
    id bigint generated by default as identity primary key,
    invoice_no text unique,
    client_id bigint references public.clients(id) on delete cascade,
    amount decimal(12,2),
    issue_date date,
    due_date date,
    status text,
    created_at timestamptz default now()
);

-- RLS Enablement
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Policies (Allow all for development)
CREATE POLICY "Enable all for services" ON public.services FOR ALL USING (true);
CREATE POLICY "Enable all for payments" ON public.payments FOR ALL USING (true);
CREATE POLICY "Enable all for invoices" ON public.invoices FOR ALL USING (true);

-- Seed Data using existing clients
DO $$
DECLARE
    sunrise_id bigint;
    mala_id bigint;
    donam_id bigint;
BEGIN
    SELECT id INTO sunrise_id FROM public.clients WHERE name LIKE '%Sunrise Heights%' LIMIT 1;
    SELECT id INTO mala_id FROM public.clients WHERE name LIKE '%Mala Palace%' LIMIT 1;
    SELECT id INTO donam_id FROM public.clients WHERE name LIKE '%Donam Maria%' LIMIT 1;

    -- Seed Services
    IF sunrise_id IS NOT NULL THEN
        INSERT INTO public.services (service_id, client_id, service_type, service_date, technician_name, status)
        VALUES ('SRV-001', sunrise_id, 'Fire Alarm Check', '2026-02-10', 'Rajesh Kumar', 'Completed')
        ON CONFLICT DO NOTHING;
    END IF;

    IF mala_id IS NOT NULL THEN
        INSERT INTO public.services (service_id, client_id, service_type, service_date, technician_name, status)
        VALUES ('SRV-002', mala_id, 'Hydrant Inspection', '2026-02-12', 'Suresh Patil', 'In Progress')
        ON CONFLICT DO NOTHING;
    END IF;

    IF donam_id IS NOT NULL THEN
        INSERT INTO public.services (service_id, client_id, service_type, service_date, technician_name, status)
        VALUES ('SRV-003', donam_id, 'Extinguisher Refill', '2026-02-14', 'Amit Singh', 'Scheduled')
        ON CONFLICT DO NOTHING;
    END IF;

    -- Seed Payments
    IF sunrise_id IS NOT NULL THEN
        INSERT INTO public.payments (payment_id, client_id, amount, payment_date, payment_method, status)
        VALUES ('PAY-1001', sunrise_id, 25000.00, '2026-02-01', 'Bank Transfer', 'Completed')
        ON CONFLICT DO NOTHING;
    END IF;

    IF mala_id IS NOT NULL THEN
        INSERT INTO public.payments (payment_id, client_id, amount, payment_date, payment_method, status)
        VALUES ('PAY-1002', mala_id, 12500.00, '2026-02-05', 'UPI', 'Completed')
        ON CONFLICT DO NOTHING;
    END IF;

    -- Seed Invoices
    IF sunrise_id IS NOT NULL THEN
        INSERT INTO public.invoices (invoice_no, client_id, amount, issue_date, due_date, status)
        VALUES ('INV-2026-001', sunrise_id, 25000.00, '2026-01-15', '2026-01-30', 'Paid')
        ON CONFLICT DO NOTHING;
    END IF;

    IF mala_id IS NOT NULL THEN
        INSERT INTO public.invoices (invoice_no, client_id, amount, issue_date, due_date, status)
        VALUES ('INV-2026-002', mala_id, 12500.00, '2026-01-20', '2026-02-05', 'Paid')
        ON CONFLICT DO NOTHING;
    END IF;

END $$;
