-- Create edit_logs table to store universal edit information
CREATE TABLE IF NOT EXISTS public.edit_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    record_id text not null,
    display_name text, -- e.g. Client Name for quick reference
    old_data jsonb,
    new_data jsonb not null,
    edited_by text,
    edited_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.edit_logs ENABLE ROW LEVEL SECURITY;

-- Create Policies to allow access (Adjust as needed for production)
DROP POLICY IF EXISTS "Enable all for edit_logs" ON public.edit_logs;
CREATE POLICY "Enable all for edit_logs" ON public.edit_logs FOR ALL USING (true);
