-- 1. Create ENUM types for Asset Tracking
DO $$ BEGIN
    CREATE TYPE asset_condition AS ENUM ('Excellent', 'Good', 'Fair', 'Poor', 'Condemned');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE service_action AS ENUM ('Serviced', 'Repaired', 'Refilled', 'Replaced');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 2. The Catalog: equipment_master
CREATE TABLE IF NOT EXISTS public.equipment_master (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category TEXT NOT NULL, 
    sub_category TEXT,      
    make_model TEXT,
    maintenance_frequency_days INTEGER NOT NULL DEFAULT 365,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. The Physical Items: client_assets
CREATE TABLE IF NOT EXISTS public.client_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE, 
    equipment_id UUID REFERENCES public.equipment_master(id),
    
    qr_code_hash TEXT UNIQUE,          
    manual_asset_tag TEXT UNIQUE,      
    
    exact_location TEXT NOT NULL,      
    current_condition asset_condition DEFAULT 'Excellent',
    installation_date DATE,
    
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. The Audit Log: asset_service_history
CREATE TABLE IF NOT EXISTS public.asset_service_history (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_id UUID REFERENCES public.client_assets(id) ON DELETE CASCADE,
    
    service_date DATE NOT NULL DEFAULT CURRENT_DATE,
    condition_reported asset_condition NOT NULL,
    parts_replaced TEXT,               
    action_taken service_action NOT NULL,
    
    next_due_date DATE NOT NULL,       
    serviced_by TEXT,                  
    
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Universal Deletion Logs
CREATE TABLE IF NOT EXISTS public.deletion_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    record_id text not null,
    display_name text,
    data jsonb not null,
    deleted_by text,
    deleted_at timestamptz default now()
);

-- 6. Universal Edit Logs
CREATE TABLE IF NOT EXISTS public.edit_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    record_id text not null,
    display_name text,
    old_data jsonb,
    new_data jsonb not null,
    edited_by text,
    edited_at timestamptz default now()
);

-- 7. RLS Policies
ALTER TABLE public.equipment_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asset_service_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deletion_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.edit_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public access on equipment_master" ON public.equipment_master;
CREATE POLICY "Allow public access on equipment_master" ON public.equipment_master FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access on client_assets" ON public.client_assets;
CREATE POLICY "Allow public access on client_assets" ON public.client_assets FOR ALL USING (true);

DROP POLICY IF EXISTS "Allow public access on asset_service_history" ON public.asset_service_history;
CREATE POLICY "Allow public access on asset_service_history" ON public.asset_service_history FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable all for deletion_logs" ON public.deletion_logs;
CREATE POLICY "Enable all for deletion_logs" ON public.deletion_logs FOR ALL USING (true);

DROP POLICY IF EXISTS "Enable all for edit_logs" ON public.edit_logs;
CREATE POLICY "Enable all for edit_logs" ON public.edit_logs FOR ALL USING (true);
