-- SQL schema for Employee Productivity Tools (Time Sheet, DPR, Schedule, Performance)

-- 1. Time Sheets
CREATE TABLE IF NOT EXISTS public.time_sheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL, -- Assuming integration with auth or a users table
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    punch_in TIME NOT NULL,
    punch_out TIME,
    total_hours NUMERIC,
    status VARCHAR(50) DEFAULT 'Present', -- Present, Absent, Half Day, Leave
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for querying by user and date
CREATE INDEX IF NOT EXISTS idx_time_sheets_user_date ON public.time_sheets(user_id, date);

-- 2. Employee Schedules
CREATE TABLE IF NOT EXISTS public.employee_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    schedule_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    type VARCHAR(50) NOT NULL, -- Meeting, Site Visit, Office Work, Collection
    location VARCHAR(255),
    status VARCHAR(50) DEFAULT 'Scheduled', -- Scheduled, Completed, Cancelled
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for fetching schedules for a specific date/user
CREATE INDEX IF NOT EXISTS idx_schedules_user_date ON public.employee_schedules(user_id, schedule_date);

-- 3. Daily Progress Reports (DPR)
CREATE TABLE IF NOT EXISTS public.daily_progress_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    report_date DATE NOT NULL DEFAULT CURRENT_DATE,
    schedule_id BIGINT REFERENCES public.employee_schedules(id) ON DELETE SET NULL, -- Link to a specific scheduled task if applicable
    task_description TEXT NOT NULL,
    outcomes TEXT,
    challenges TEXT,
    status VARCHAR(50) DEFAULT 'Completed', -- Completed, Pending, In Progress
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Employee Performance Targets (Optional: if we want to store specific targets to measure against)
CREATE TABLE IF NOT EXISTS public.employee_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    target_month VARCHAR(7) NOT NULL, -- e.g., '2026-03'
    target_type VARCHAR(50), -- e.g., 'Site Visits', 'Leads Won', 'Revenue'
    target_value NUMERIC NOT NULL,
    achieved_value NUMERIC DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, target_month, target_type)
);

-- Adding RLS policies would go here if Supabase RLS is enabled. 
-- For now, we assume standard access control via server actions.
