-- ==================================================================================
-- MASTER SCHEMA FOR RUDRA FIRE PROTECTION (Consolidated Migration)
-- This script sets up all tables, types, RLS policies, and seed data.
-- ==================================================================================

-- 1. ENUM TYPES
DO $$ BEGIN
    CREATE TYPE quotation_status AS ENUM ('Draft', 'Sent', 'Accepted', 'Rejected', 'Expired', 'Needs Approval', 'Requirement Change', 'Submit', 'Approved');
EXCEPTION WHEN duplicate_object THEN 
    -- If exists, handle adding new values separately
    BEGIN
        ALTER TYPE quotation_status ADD VALUE 'Needs Approval';
        ALTER TYPE quotation_status ADD VALUE 'Requirement Change';
        ALTER TYPE quotation_status ADD VALUE 'Submit';
        ALTER TYPE quotation_status ADD VALUE 'Approved';
    EXCEPTION WHEN duplicate_object THEN null;
    END;
END $$;

DO $$ BEGIN
    CREATE TYPE asset_condition AS ENUM ('Excellent', 'Good', 'Fair', 'Poor', 'Condemned');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE service_action AS ENUM ('Serviced', 'Repaired', 'Refilled', 'Replaced');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- 2. CORE TABLES
CREATE TABLE IF NOT EXISTS public.clients (
    id bigint generated by default as identity primary key,
    name text not null,
    building_type text,
    address text,
    contact_name text,
    contact_person text,
    contract_value text,
    category text,
    status text,
    priority text,
    -- From update_clients_v7
    developer_name text,
    wings text,
    ground_floor text,
    stilt text,
    landmark text,
    sd_meter_room boolean DEFAULT false,
    sd_lift_machine_room boolean DEFAULT false,
    sd_electric_duct boolean DEFAULT false,
    hydrant_valve_type text DEFAULT 'Single',
    hosreel_drum_count integer DEFAULT 0,
    courtyard_hydrant_valve_type text DEFAULT 'Single',
    courtyard_hydrant_valve_count integer DEFAULT 0,
    hosebox_type text DEFAULT 'Single',
    hosebox_count integer DEFAULT 0,
    canvas_hosepipe_count integer DEFAULT 0,
    fire_extinguisher_clean_agent integer DEFAULT 0,
    pump_type text DEFAULT 'Centrifugal',
    pump_hydrant integer DEFAULT 0,
    pump_sprinkler integer DEFAULT 0,
    pump_hydrant_jockey integer DEFAULT 0,
    pump_sprinkler_jockey integer DEFAULT 0,
    pump_standby_hydrant integer DEFAULT 0,
    pump_standby_sprinkler integer DEFAULT 0,
    pump_standby_jockey integer DEFAULT 0,
    ss_ground boolean DEFAULT false,
    ss_basement boolean DEFAULT false,
    ss_podium boolean DEFAULT false,
    ss_lift_lobby boolean DEFAULT false,
    ss_flat boolean DEFAULT false,
    created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.profiles (
    id uuid references auth.users on delete cascade primary key,
    role text check (role in ('admin', 'employee', 'client')) default 'client',
    full_name text,
    company text,
    created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.leads (
    id bigint generated by default as identity primary key,
    sr_no text,
    sales_form_no text,
    sales_form_date text,
    source text,
    stage text,
    category text,
    location text,
    project_name text,
    developer text,
    configuration text,
    const_status text,
    owner_name text,
    finalizing_authority text,
    site_incharge text,
    architect text,
    remarks text,
    created_at timestamptz default now()
);

-- 3. MODULE TABLES (Quotations, Services, Payments, Invoices)
CREATE TABLE IF NOT EXISTS public.quotations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quotation_number TEXT UNIQUE NOT NULL,
    client_id BIGINT REFERENCES public.clients(id) ON DELETE RESTRICT,
    quotation_date DATE NOT NULL DEFAULT CURRENT_DATE,
    expiration_date DATE,
    payment_terms TEXT,
    subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,
    status quotation_status DEFAULT 'Draft',
    notes TEXT,
    -- From update_quotations_v1
    quote_name TEXT,
    quote_code TEXT,
    account TEXT,
    deal TEXT,
    quote_type TEXT,
    door_type TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.quotation_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    quotation_id UUID REFERENCES public.quotations(id) ON DELETE CASCADE,
    product_description TEXT NOT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0,
    total_price DECIMAL(12,2) NOT NULL DEFAULT 0,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.services (
    id bigint generated by default as identity primary key,
    service_id text unique,
    client_id bigint references public.clients(id) on delete cascade,
    service_type text,
    service_date date,
    technician_name text,
    status text,
    created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.payments (
    id bigint generated by default as identity primary key,
    payment_id text unique,
    client_id bigint references public.clients(id) on delete cascade,
    amount decimal(12,2),
    payment_date date,
    payment_method text,
    status text,
    created_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.invoices (
    id bigint generated by default as identity primary key,
    invoice_no text unique,
    client_id bigint references public.clients(id) on delete cascade,
    amount decimal(12,2),
    issue_date date,
    due_date date,
    status text,
    created_at timestamptz default now()
);

-- 4. PRODUCTIVITY & ASSET TRACKING
CREATE TABLE IF NOT EXISTS public.time_sheets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    punch_in TIME NOT NULL,
    punch_out TIME,
    total_hours NUMERIC,
    status VARCHAR(50) DEFAULT 'Present',
    remarks TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.employee_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    schedule_date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    type VARCHAR(50) NOT NULL,
    location VARCHAR(255),
    status VARCHAR(50) DEFAULT 'Scheduled',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.daily_progress_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    report_date DATE NOT NULL DEFAULT CURRENT_DATE,
    schedule_id BIGINT REFERENCES public.employee_schedules(id) ON DELETE SET NULL,
    task_description TEXT NOT NULL,
    outcomes TEXT,
    challenges TEXT,
    status VARCHAR(50) DEFAULT 'Completed',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audit_reports (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE,
    report_date DATE NOT NULL,
    auditor_name TEXT NOT NULL,
    report_type TEXT,
    status TEXT DEFAULT 'Draft',
    findings TEXT,
    recommendations TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.equipment_master (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category TEXT NOT NULL, 
    sub_category TEXT,      
    make_model TEXT,
    maintenance_frequency_days INTEGER NOT NULL DEFAULT 365,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.client_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id BIGINT REFERENCES public.clients(id) ON DELETE CASCADE, 
    equipment_id UUID REFERENCES public.equipment_master(id),
    qr_code_hash TEXT UNIQUE,          
    manual_asset_tag TEXT UNIQUE,      
    exact_location TEXT NOT NULL,      
    current_condition asset_condition DEFAULT 'Excellent',
    installation_date DATE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. LOGGING TABLES
CREATE TABLE IF NOT EXISTS public.deletion_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    record_id text not null,
    display_name text,
    data jsonb not null,
    deleted_by text,
    deleted_at timestamptz default now()
);

CREATE TABLE IF NOT EXISTS public.edit_logs (
    id bigint generated by default as identity primary key,
    table_name text not null,
    record_id text not null,
    display_name text,
    old_data jsonb,
    new_data jsonb not null,
    edited_by text,
    edited_at timestamptz default now()
);

-- 6. RLS POLICIES (Development Friendly)
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.equipment_master ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.client_assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deletion_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.edit_logs ENABLE ROW LEVEL SECURITY;

DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'
    LOOP
        EXECUTE format('DROP POLICY IF EXISTS "Public Full Access" ON public.%I', t);
        EXECUTE format('CREATE POLICY "Public Full Access" ON public.%I FOR ALL USING (true)', t);
    END LOOP;
END $$;

-- 7. SEED INITIAL DATA
INSERT INTO public.clients (name, building_type, address, contact_name, contact_person, contract_value, category, status, priority)
SELECT 'Sunrise Heights Co-op', 'Residential', 'Plot 4, Sector 12, Kharghar', 'Rahul Sharma', 'Suresh Patil (Manager)', '₹1,50,000', 'AMC', 'Active', 'High'
WHERE NOT EXISTS (SELECT 1 FROM public.clients WHERE name = 'Sunrise Heights Co-op');

INSERT INTO public.leads (sr_no, sales_form_no, sales_form_date, source, stage, category, location, project_name, developer, configuration, const_status, owner_name, finalizing_authority, site_incharge, architect, remarks)
SELECT '1', 'AS001', '10/12/2012', 'WOM', 'qualified', 'HOT', 'Santakruz', 'Runwal symphony', 'Runwal developers pvt.ltd', 'Gr+Bas+Pod+15fl', '15 Fl compl', 'Sandeep runwal', 'Manisha Thakur', 'Mr.sameer patil', 'Vivek bhole', ''
WHERE NOT EXISTS (SELECT 1 FROM public.leads WHERE sr_no = '1');
