-- Create Clients Table
CREATE TABLE IF NOT EXISTS public.clients (
    id bigint generated by default as identity primary key,
    name text not null,
    building_type text,
    address text,
    contact_name text,
    contact_person text,
    contract_value text,
    category text,
    status text,
    priority text,
    created_at timestamptz default now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;

-- Create Policies to allow access (Adjust as needed for production)
-- Drop existing policies to avoid errors on re-run
DROP POLICY IF EXISTS "Enable read access for all users" ON public.clients;
DROP POLICY IF EXISTS "Enable insert access for all users" ON public.clients;
DROP POLICY IF EXISTS "Enable update access for all users" ON public.clients;
DROP POLICY IF EXISTS "Enable delete access for all users" ON public.clients;

CREATE POLICY "Enable read access for all users" ON public.clients FOR SELECT USING (true);
CREATE POLICY "Enable insert access for all users" ON public.clients FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON public.clients FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON public.clients FOR DELETE USING (true);

-- Seed Initial Data
INSERT INTO public.clients (name, building_type, address, contact_name, contact_person, contract_value, category, status, priority)
SELECT 'Sunrise Heights Co-op', 'Residential', 'Plot 4, Sector 12, Kharghar', 'Rahul Sharma', 'Suresh Patil (Manager)', '₹1,50,000', 'AMC', 'Active', 'High'
WHERE NOT EXISTS (SELECT 1 FROM public.clients WHERE name = 'Sunrise Heights Co-op');

INSERT INTO public.clients (name, building_type, address, contact_name, contact_person, contract_value, category, status, priority)
SELECT 'Green Valley Apartments', 'Residential', 'MG Road, Thane West', 'Priya Patel', 'Ramesh Powar (Secretary)', '₹85,000', 'Refill', 'Active', 'Medium'
WHERE NOT EXISTS (SELECT 1 FROM public.clients WHERE name = 'Green Valley Apartments');

INSERT INTO public.clients (name, building_type, address, contact_name, contact_person, contract_value, category, status, priority)
SELECT 'Blue Ridge Towers', 'Commercial', 'IT Park, Hinjewadi, Pune', 'Vikram Singh', 'Amit Deshmukh (Admin)', '₹5,00,000', 'New', 'Inactive', 'Low'
WHERE NOT EXISTS (SELECT 1 FROM public.clients WHERE name = 'Blue Ridge Towers');

INSERT INTO public.clients (name, building_type, address, contact_name, contact_person, contract_value, category, status, priority)
SELECT 'Ocean View Residency', 'Residential', 'Carter Road, Bandra', 'Amit Desai', 'Sunil Shetty (Chairman)', '₹2,10,000', 'Repair', 'Active', 'High'
WHERE NOT EXISTS (SELECT 1 FROM public.clients WHERE name = 'Ocean View Residency');

INSERT INTO public.clients (name, building_type, address, contact_name, contact_person, contract_value, category, status, priority)
SELECT 'Skyline Plaza', 'Commercial', 'Vashi Sector 17', 'Neha Gupta', 'Pooja Kulkarni (HR)', '₹3,25,000', 'AMC', 'Pending', 'Medium'
WHERE NOT EXISTS (SELECT 1 FROM public.clients WHERE name = 'Skyline Plaza');
